"""Bus matrix exporter for conceptual models.

v1.0: Simplified without realized_by - shows relationships only.
"""

from typing import TextIO

from dbt_conceptual.state import ProjectState


def export_bus_matrix(state: ProjectState, output: TextIO) -> None:
    """Export bus matrix as HTML table.

    Note: v1.0 removed realized_by from relationships. This export now
    shows a relationship summary instead of the traditional bus matrix.
    The full bus matrix will return in a future version.

    Args:
        state: Project state with concepts and relationships
        output: Text stream to write HTML to
    """
    # Sort relationships for consistent output
    relationships_list = sorted(
        state.relationships.items(), key=lambda x: (x[1].from_concept, x[1].name)
    )

    # Calculate statistics
    total_relationships = len(relationships_list)
    complete_relationships = sum(
        1
        for _rid, r in relationships_list
        if r.get_status(state.concepts) == "complete"
    )

    output.write("""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>dbt-conceptual Relationships</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            background: #fafaf9;
            color: #333333;
            line-height: 1.6;
            padding: 2rem;
        }

        .container {
            max-width: 100%;
            margin: 0 auto;
            background: white;
            border-radius: 8px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
            padding: 2rem;
        }

        h1 {
            font-size: 2rem;
            margin-bottom: 0.5rem;
            color: #1a1a1a;
        }

        .subtitle {
            color: #666;
            margin-bottom: 2rem;
            font-size: 0.9rem;
        }

        .info {
            background: #e8f4fd;
            border-left: 4px solid #2196F3;
            padding: 1rem;
            margin-bottom: 2rem;
            border-radius: 4px;
        }

        .info h2 {
            font-size: 1rem;
            margin-bottom: 0.5rem;
            color: #1976D2;
        }

        .info p {
            font-size: 0.875rem;
            color: #333;
            margin: 0;
        }

        .stats {
            display: flex;
            gap: 2rem;
            margin-bottom: 2rem;
            flex-wrap: wrap;
        }

        .stat {
            flex: 1;
            min-width: 150px;
        }

        .stat-label {
            font-size: 0.75rem;
            color: #666;
            text-transform: uppercase;
            letter-spacing: 0.5px;
            margin-bottom: 0.25rem;
        }

        .stat-value {
            font-size: 2rem;
            font-weight: bold;
            color: #1a1a1a;
        }

        .matrix-container {
            overflow-x: auto;
            margin-bottom: 2rem;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 0.875rem;
        }

        th {
            background: #f5f4f2;
            padding: 1rem 0.75rem;
            text-align: left;
            font-weight: 600;
            border-bottom: 2px solid #e8e6e3;
        }

        td {
            padding: 0.75rem;
            border-bottom: 1px solid #f0eeec;
        }

        tr:hover td {
            background: #fafaf9;
        }

        .status-complete {
            color: #4CAF50;
        }

        .status-stub {
            color: #e67e22;
        }

        .empty-state {
            text-align: center;
            padding: 3rem;
            color: #999;
        }

        .empty-state-icon {
            font-size: 3rem;
            margin-bottom: 1rem;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Relationships</h1>
        <p class="subtitle">Generated by dbt-conceptual</p>

        <div class="info">
            <h2>About Relationships</h2>
            <p>
                Relationships define how concepts connect to each other.
                A relationship is "complete" when both its endpoints are defined concepts.
            </p>
        </div>

        <div class="stats">
            <div class="stat">
                <div class="stat-label">Total Relationships</div>
                <div class="stat-value">""")
    output.write(str(total_relationships))
    output.write("""</div>
            </div>
            <div class="stat">
                <div class="stat-label">Complete</div>
                <div class="stat-value">""")
    output.write(str(complete_relationships))
    output.write("""</div>
            </div>
        </div>
""")

    if not relationships_list:
        output.write("""
        <div class="empty-state">
            <div class="empty-state-icon">🔗</div>
            <p>No relationships defined</p>
            <p style="font-size: 0.875rem; margin-top: 0.5rem; color: #999;">
                Add relationships to your conceptual.yml to see them here
            </p>
        </div>
""")
    else:
        output.write("""
        <div class="matrix-container">
            <table>
                <thead>
                    <tr>
                        <th>From</th>
                        <th>Verb</th>
                        <th>To</th>
                        <th>Cardinality</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
""")

        # Write relationship rows
        for _rel_id, rel in relationships_list:
            status = rel.get_status(state.concepts)
            status_class = "status-complete" if status == "complete" else "status-stub"
            status_icon = "✓" if status == "complete" else "○"

            output.write("                    <tr>\n")
            output.write(f"                        <td>{rel.from_concept}</td>\n")
            output.write(
                f"                        <td><strong>{rel.verb}</strong></td>\n"
            )
            output.write(f"                        <td>{rel.to_concept}</td>\n")
            output.write(f"                        <td>{rel.cardinality}</td>\n")
            output.write(
                f'                        <td class="{status_class}">{status_icon} {status}</td>\n'
            )
            output.write("                    </tr>\n")

        output.write("""                </tbody>
            </table>
        </div>
""")

    output.write("""    </div>
</body>
</html>
""")
