name: 'dbt-conceptual Diff'
description: 'Generate conceptual model diff for PR reviews'
author: 'dbt-conceptual'

branding:
  icon: 'git-branch'
  color: 'orange'

inputs:
  base:
    description: 'Base git ref to compare against (e.g., main, origin/main)'
    required: true
  format:
    description: 'Output format: markdown or json'
    required: false
    default: 'markdown'
  comment:
    description: 'Post diff as PR comment (true/false)'
    required: false
    default: 'false'
  project-dir:
    description: 'Path to dbt project directory'
    required: false
    default: '.'
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.11'
  version:
    description: 'dbt-conceptual version to install (e.g., 0.1.0, latest)'
    required: false
    default: 'latest'

outputs:
  has_changes:
    description: 'Whether there are changes in the conceptual model'
    value: ${{ steps.diff.outputs.has_changes }}
  summary:
    description: 'The diff summary'
    value: ${{ steps.diff.outputs.summary }}

runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dbt-conceptual
      shell: bash
      run: |
        if [ "${{ inputs.version }}" = "latest" ]; then
          pip install dbt-conceptual
        else
          pip install dbt-conceptual==${{ inputs.version }}
        fi

    - name: Run conceptual diff
      id: diff
      shell: bash
      env:
        BASE_REF: ${{ inputs.base }}
        FORMAT: ${{ inputs.format }}
        PROJECT_DIR: ${{ inputs.project-dir }}
      run: |
        # Run diff command
        cd "$PROJECT_DIR"

        OUTPUT=$(dbt-conceptual export --type diff --format "$FORMAT" --base "$BASE_REF" 2>&1) || true

        # Check if there are changes
        if echo "$OUTPUT" | grep -q "No changes"; then
          echo "has_changes=false" >> $GITHUB_OUTPUT
        else
          echo "has_changes=true" >> $GITHUB_OUTPUT
        fi

        # Save output for later steps
        {
          echo "summary<<EOF"
          echo "$OUTPUT"
          echo "EOF"
        } >> $GITHUB_OUTPUT

        # Write to job summary
        if [ "$FORMAT" = "markdown" ]; then
          echo "## Conceptual Model Changes" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "$OUTPUT" >> $GITHUB_STEP_SUMMARY
        fi

    - name: Post PR comment
      if: inputs.comment == 'true' && github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const summary = `${{ steps.diff.outputs.summary }}`;
          const hasChanges = `${{ steps.diff.outputs.has_changes }}`;

          // Only comment if there are changes
          if (hasChanges === 'false') {
            console.log('No conceptual model changes detected');
            return;
          }

          const marker = '<!-- dbt-conceptual-diff -->';
          const body = `${marker}\n## Conceptual Model Changes\n\n${summary}`;

          // Find existing comment
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });

          const existingComment = comments.find(c => c.body.includes(marker));

          if (existingComment) {
            // Update existing comment
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: existingComment.id,
              body: body,
            });
            console.log('Updated existing PR comment');
          } else {
            // Create new comment
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: body,
            });
            console.log('Created new PR comment');
          }
